name: VyOS LTS Build

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        default: "1.4.4"
        description: VyOS version
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      # For VyOS 1.2 (crux) use vyos/vyos-build:crux
      # For VyOS 1.3 (equuleus) use vyos/vyos-build:equuleus
      # For VyOS 1.4 (sagitta) use vyos/vyos-build:sagitta
      # For our VyOS rolling release you should use vyos/vyos-build which will always refer to the latest image.
      # Ref: https://docs.vyos.io/en/latest/contributing/build-vyos.html#build
      image: vyos/vyos-build:sagitta
      env:
        TZ: Europe/Rome
      options: --privileged
    env:
      TZ: Europe/Rome
    permissions:
      actions: read
      contents: write

    steps:
      - name: Download APT key
        run: |
          set -eux
          wget https://vyos.tnyzeq.icu/apt/apt.gpg.key -O /opt/apt.gpg.key

      - name: Git clone vyos-build
        run: |
          set -eux
          git clone -b sagitta --single-branch https://github.com/dd010101/vyos-build.git

      - name: Cleanup env
        working-directory: vyos-build
        run: |
          set -eux
          make clean

      - name: Make ISO
        working-directory: vyos-build
        run: |
          set -eux
          ./build-vyos-image iso \
            --architecture amd64 \
            --build-by "${{ github.actor }}@users.noreply.github.com" \
            --build-type release \
            --vyos-mirror "https://vyos.tnyzeq.icu/apt/sagitta" \
            --custom-apt-key /opt/apt.gpg.key \
            --version "${{ inputs.version }}"

      - name: Generate checksums
        run: |
          set -eux
          pwd
          ls -lah
          ls -lah vyos-build/build
          ISOFILE="vyos-build/build/vyos-${{ inputs.version }}-iso-amd64.iso"
          echo "SHA1=$(sha1sum $ISOFILE | cut -d' ' -f1)" >> $GITHUB_ENV
          echo "SHA256=$(sha256sum $ISOFILE | cut -d' ' -f1)" >> $GITHUB_ENV

      - name: Pre-Release
        uses: softprops/action-gh-release@v2
        with:
          name: VyOS ${{ inputs.version }} LTS
          tag_name: ${{ inputs.version }}
          body: |
            VyOS ${{ inputs.version }} LTS
            
            **Checksums:**
            - SHA1: ${{ env.SHA1 }}
            - SHA256: ${{ env.SHA256 }}
          draft: true
          prerelease: true
          files: |
            vyos-build/build/vyos-${{ inputs.version }}-iso-amd64.iso
